package com.example.gaitlabapp.model.forms.comparisons;

import lombok.Data;
import lombok.Getter;

import jakarta.persistence.*;
import lombok.NoArgsConstructor;

@Getter
@Data
@NoArgsConstructor
@Entity
@Table(name = "promcomparison")
public class IPromComparison {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "prom_comp_id")
    private Integer promCompId;
    @Column(name = "hip_abdR")
    private Integer hipAbdR;
    @Column(name = "hip_abdRSd")
    private String hipAbdRSd;
    @Column(name = "hip_abdL")
    private Integer hipAbdL;
    @Column(name = "hip_abdLSd")
    private String hipAbdLSd;
    @Column(name = "hip_abdSR")
    private String hipAbdSR;
    @Column(name = "hip_abdSRSd")
    private String hipAbdSRSd;
    @Column(name = "hip_abdSL")
    private String hipAbdSL;
    @Column(name = "hip_abdSLSd")
    private String hipAbdSLSd;
//    @Column(name = "compHipExtr")
//    private Integer compHipExtr;
//    @Column(name = "hipExtrSd")
//    private String hipExtrSd;
    @Column(name = "hip_extL")
    private Integer hipExtL;
    @Column(name = "hip_extLSd")
    private String hipExtLSd;
    @Column(name = "hip_extSR")
    private String hipExtSR;
    @Column(name = "hip_extSRSd")
    private String hipExtSRSd;
    @Column(name = "popRLow")
    private Integer popRLow;
    @Column(name = "popRHigh")
    private Integer popRHigh;
    @Column(name = "popRSd")
    private String popRSd;
    @Column(name = "popLLow")
    private Integer popLLow;
    @Column(name = "popLHigh")
    private Integer popLHigh;
    @Column(name = "popLSd")
    private String popLSd;
    @Column(name = "dorsiFR")
    private Integer dorsiFR;
    @Column(name = "dorsiFRSd")
    private String dorsiFRSd;
    @Column(name = "dorsiFL")
    private Integer dorsiFL;
    @Column(name = "dorsiFLSd")
    private String dorsiFLSd;
    @Column(name = "dorsiER")
    private Integer dorsiER;
    @Column(name = "dorsiERSd")
    private String dorsiERSd;
    @Column(name = "dorsiEL")
    private Integer dorsiEL;
    @Column(name = "dorsiELSd")
    private String dorsiELSd;
    @Column(name = "dorsiFSR")
    private String dorsiFSR;
    @Column(name = "dorsiFSRSd")
    private String dorsiFSRSd;
    @Column(name = "dorsiFSL")
    private String dorsiFSL;
    @Column(name = "dorsiFSLSd")
    private String dorsiFSLSd;
    @Column(name = "shoulder_abductionl")
    private Integer shoulderAbductionl;
    @Column(name = "shoulder_abdubctionr")
    private Integer shoulderAbdubctionr;
    @Column(name = "shoulder_abductionRSd")
    private String shoulderAbductionRSd;
    @Column(name = "shoulder_abductionLSd")
    private String shoulderAbductionLSd;
    @Column(name = "shoulder_abductionSL")
    private String shoulderAbductionSL;
    @Column(name = "shoulder_abdubctionSR")
    private String shoulderAbdubctionSR;
    @Column(name = "shoulder_abductionSLSd")
    private String shoulderAbductionSLSd;
    @Column(name = "shoulder_abductionSRSd")
    private String shoulderAbductionSRSd;
    @Column(name = "elbow_extL")
    private Integer elbowExtL;
    @Column(name = "elbow_extR")
    private Integer elbowExtR;
    @Column(name = "elbow_extLSd")
    private String elbowExtLSd;
    @Column(name = "elbow_extRSd")
    private String elbowExtRSd;
    @Column(name = "elbow_extSL")
    private String elbowExtSL;
    @Column(name = "elbow_extSR")
    private String elbowExtSR;
    @Column(name = "elbow_extSLSd")
    private String elbowExtSLSd;
    @Column(name = "elbow_extSRSd")
    private String elbowExtSRSd;
    @Column(name = "wrist_extL")
    private Integer wristExtL;
    @Column(name = "wrist_extR")
    private Integer wristExtR;
    @Column(name = "wrist_extLSd")
    private String wristExtLSd;
    @Column(name = "wrist_extRSd")
    private String wristExtRSd;
    @Column(name = "wrist_extSR")
    private String wristExtSR;
    @Column(name = "wrist_extSL")
    private String wristExtSL;
    @Column(name = "wrist_extSLSd")
    private String wristExtSLSd;
    @Column(name = "wrist_extSRSd")
    private String wristExtSRSd;
    @Column(name = "tma")
    private String tma;
    @Column(name = "tfa")
    private String tfa;
    @Column(name = "tfaL")
    private String tfaL;
    @Column(name = "tfaR")
    private String tfaR;
    @Column(name = "tfaRSd")
    private String tfaRSd;
    @Column(name = "tfaLSd")
    private String tfaLSd;
    @Column(name = "calcaneal_inv")
    private String calcanealInv;
    @Column(name = "calcaneal_ever")
    private String calcanealEver;
    @Column(name = "knee_vargus")
    private String kneeVargus;
    @Column(name = "ryder_test")
    private String ryderTest;
    @Column(name = "ely_test")
    private String elyTest;
    @Column(name = "elyL")
    private Integer elyL;
    @Column(name = "elyR")
    private Integer elyR;
    @Column(name = "elyRSd")
    private String elyRSd;
    @Column(name = "elyLSd")
    private String elyLSd;
    @Column(name = "plantar")
    private String plantar;
    @Column(name = "plantarR")
    private Integer plantarR;
    @Column(name = "plantarL")
    private Integer plantarL;
    @Column(name = "plantarLSd")
    private String plantarLSd;
    @Column(name = "plantarRSd")
    private String plantarRSd;
    @Column(name = "hip_flexR")
    private String hipFlexR;
    @Column(name = "hip_flexRSd")
    private String hipFlexRSd;
    @Column(name = "hip_flexL")
    private String hipFlexL;
    @Column(name = "hip_flexLSd")
    private String hipFlexLSd;
    @Column(name = "comp_hip_extr")
    private String hipExtR;
    @Column(name = "hip_extRSd")
    private String hipExtRSd;
    @Column(name = "hip_int_rotL")
    private String hipIntRotL;
    @Column(name = "hip_int_rotR")
    private String hipIntRotR;
    @Column(name = "hip_int_rotRSd")
    private String hipIntRotRSd;
    @Column(name = "hip_int_rotLSd")
    private String hipIntRotLSd;
    @Column(name = "knee_int_rotL")
    private String kneeIntRotL;
    @Column(name = "knee_int_rotRSd")
    private String kneeIntRotRSd;
    @Column(name = "knee_int_rotLSd")
    private String kneeIntRotLSd;
    @Column(name = "knee_int_rotR")
    private String kneeIntRotR;
    @Column(name = "knee_extR")
    private String kneeExtR;
    @Column(name = "knee_extL")
    private String kneeExtL;
    @Column(name = "knee_extRSd")
    private String kneeExtRSd;
    @Column(name = "knee_extLSd")
    private String kneeExtLSd;
    @Column(name = "knee_flexR")
    private String kneeFlexR;
    @Column(name = "knee_flexL")
    private String kneeFlexL;
    @Column(name = "knee_flexRSd")
    private String kneeFlexRSd;
    @Column(name = "knee_flexLSd")
    private String kneeFlexLSd;
    @Column(name = "ankle_everR")
    private String ankleEverR;
    @Column(name = "ankle_everL")
    private String ankleEverL;
    @Column(name = "ankle_everRSd")
    private String ankleEverRSd;
    @Column(name = "ankle_everLSd")
    private String ankleEverLSd;
    @Column(name = "ankle_invL")
    private String ankleInvL;
    @Column(name = "ankle_invR")
    private String ankleInvR;
    @Column(name = "ankle_invLSd")
    private String ankleInvLSd;
    @Column(name = "ankle_invRSD")
    private String ankleInvRSD;
    @Column(name = "ff_abaddLSd")
    private String ffAbaddLSd;
    @Column(name = "ff_abaddRSd")
    private String ffAbaddRSd;
    @Column(name = "ff_abaddL")
    private String ffAbaddL;
    @Column(name = "ff_abaddR")
    private String ffAbaddR;
    @Column(name = "leg_lengthR")
    private String legLengthR;
    @Column(name = "leg_lengthL")
    private String legLengthL;
    @Column(name = "q_angleR")
    private String qAngleR;
    @Column(name = "q_ankleL")
    private String qAnkleL;
    @Column(name = "bilateral_popR")
    private String bilateralPopR;
    @Column(name = "bilateral_popL")
    private String bilateralPopL;
    @Column(name = "bilateral_popRSd")
    private String bilateralPopRSd;
    @Column(name = "bilater_popLSd")
    private String bilaterPopLSd;
}
