package com.example.gaitlabapp.model.forms.comparisons;

import lombok.Data;
import lombok.Getter;

import jakarta.persistence.*;
import lombok.NoArgsConstructor;

@Getter
@Data
@NoArgsConstructor
@Entity
@Table(name = "PROMComparison")
public class IPromComparison {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "promCompId")
    private Integer promCompId;
    @Column(name = "hipAbdR")
    private Integer hipAbdR;
    @Column(name = "hipAbdRSd")
    private String hipAbdRSd;
    @Column(name = "hipAbdL")
    private Integer hipAbdL;
    @Column(name = "hipAbdLSd")
    private String hipAbdLSd;
    @Column(name = "hipAbdSR")
    private String hipAbdSR;
    @Column(name = "hipAbdSRSd")
    private String hipAbdSRSd;
    @Column(name = "hipAbdSL")
    private String hipAbdSL;
    @Column(name = "hipAbdSLSd")
    private String hipAbdSLSd;
//    @Column(name = "compHipExtr")
//    private Integer compHipExtr;
//    @Column(name = "hipExtrSd")
//    private String hipExtrSd;
    @Column(name = "hipExtL")
    private Integer hipExtL;
    @Column(name = "hipExtLSd")
    private String hipExtLSd;
    @Column(name = "hipExtSR")
    private String hipExtSR;
    @Column(name = "hipExtSRSd")
    private String hipExtSRSd;
    @Column(name = "popRLow")
    private Integer popRLow;
    @Column(name = "popRHigh")
    private Integer popRHigh;
    @Column(name = "popRSd")
    private String popRSd;
    @Column(name = "popLLow")
    private Integer popLLow;
    @Column(name = "popLHigh")
    private Integer popLHigh;
    @Column(name = "popLSd")
    private String popLSd;
    @Column(name = "dorsiFR")
    private Integer dorsiFR;
    @Column(name = "dorsiFRSd")
    private String dorsiFRSd;
    @Column(name = "dorsiFL")
    private Integer dorsiFL;
    @Column(name = "dorsiFLSd")
    private String dorsiFLSd;
    @Column(name = "dorsiER")
    private Integer dorsiER;
    @Column(name = "dorsiERSd")
    private String dorsiERSd;
    @Column(name = "dorsiEL")
    private Integer dorsiEL;
    @Column(name = "dorsiELSd")
    private String dorsiELSd;
    @Column(name = "dorsiFSR")
    private String dorsiFSR;
    @Column(name = "dorsiFSRSd")
    private String dorsiFSRSd;
    @Column(name = "dorsiFSL")
    private String dorsiFSL;
    @Column(name = "dorsiFSLSd")
    private String dorsiFSLSd;
    @Column(name = "shoulderAbductionl")
    private Integer shoulderAbductionl;
    @Column(name = "shoulderAbdubctionr")
    private Integer shoulderAbdubctionr;
    @Column(name = "shoulderAbductionRSd")
    private String shoulderAbductionRSd;
    @Column(name = "shoulderAbductionLSd")
    private String shoulderAbductionLSd;
    @Column(name = "shoulderAbductionSL")
    private String shoulderAbductionSL;
    @Column(name = "shoulderAbdubctionSR")
    private String shoulderAbdubctionSR;
    @Column(name = "shoulderAbductionSLSd")
    private String shoulderAbductionSLSd;
    @Column(name = "shoulderAbductionSRSd")
    private String shoulderAbductionSRSd;
    @Column(name = "elbowExtL")
    private Integer elbowExtL;
    @Column(name = "elbowExtR")
    private Integer elbowExtR;
    @Column(name = "elbowExtLSd")
    private String elbowExtLSd;
    @Column(name = "elbowExtRSd")
    private String elbowExtRSd;
    @Column(name = "elbowExtSL")
    private String elbowExtSL;
    @Column(name = "elbowExtSR")
    private String elbowExtSR;
    @Column(name = "elbowExtSLSd")
    private String elbowExtSLSd;
    @Column(name = "elbowExtSRSd")
    private String elbowExtSRSd;
    @Column(name = "wristExtL")
    private Integer wristExtL;
    @Column(name = "wristExtR")
    private Integer wristExtR;
    @Column(name = "wristExtLSd")
    private String wristExtLSd;
    @Column(name = "wristExtRSd")
    private String wristExtRSd;
    @Column(name = "wristExtSR")
    private String wristExtSR;
    @Column(name = "wristExtSL")
    private String wristExtSL;
    @Column(name = "wristExtSLSd")
    private String wristExtSLSd;
    @Column(name = "wristExtSRSd")
    private String wristExtSRSd;
    @Column(name = "tma")
    private String tma;
    @Column(name = "tfa")
    private String tfa;
    @Column(name = "tfaL")
    private String tfaL;
    @Column(name = "tfaR")
    private String tfaR;
    @Column(name = "tfaRSd")
    private String tfaRSd;
    @Column(name = "tfaLSd")
    private String tfaLSd;
    @Column(name = "calcanealInv")
    private String calcanealInv;
    @Column(name = "calcanealEver")
    private String calcanealEver;
    @Column(name = "kneeVargus")
    private String kneeVargus;
    @Column(name = "ryderTest")
    private String ryderTest;
    @Column(name = "elyTest")
    private String elyTest;
    @Column(name = "elyL")
    private Integer elyL;
    @Column(name = "elyR")
    private Integer elyR;
    @Column(name = "elyRSd")
    private String elyRSd;
    @Column(name = "elyLSd")
    private String elyLSd;
    @Column(name = "plantar")
    private String plantar;
    @Column(name = "plantarR")
    private Integer plantarR;
    @Column(name = "plantarL")
    private Integer plantarL;
    @Column(name = "plantarLSd")
    private String plantarLSd;
    @Column(name = "plantarRSd")
    private String plantarRSd;
    @Column(name = "hipFlexR")
    private String hipFlexR;
    @Column(name = "hipFlexRSd")
    private String hipFlexRSd;
    @Column(name = "hipFlexL")
    private String hipFlexL;
    @Column(name = "hipFlexLSd")
    private String hipFlexLSd;
    @Column(name = "compHipExtr")
    private String hipExtR;
    @Column(name = "hipExtRSd")
    private String hipExtRSd;
    @Column(name = "hipIntRotL")
    private String hipIntRotL;
    @Column(name = "hipIntRotR")
    private String hipIntRotR;
    @Column(name = "hipIntRotRSd")
    private String hipIntRotRSd;
    @Column(name = "hipIntRotLSd")
    private String hipIntRotLSd;
    @Column(name = "kneeIntRotL")
    private String kneeIntRotL;
    @Column(name = "kneeIntRotRSd")
    private String kneeIntRotRSd;
    @Column(name = "kneeIntRotLSd")
    private String kneeIntRotLSd;
    @Column(name = "kneeIntRotR")
    private String kneeIntRotR;
    @Column(name = "kneeExtR")
    private String kneeExtR;
    @Column(name = "kneeExtL")
    private String kneeExtL;
    @Column(name = "kneeExtRSd")
    private String kneeExtRSd;
    @Column(name = "kneeExtLSd")
    private String kneeExtLSd;
    @Column(name = "kneeFlexR")
    private String kneeFlexR;
    @Column(name = "kneeFlexL")
    private String kneeFlexL;
    @Column(name = "kneeFlexRSd")
    private String kneeFlexRSd;
    @Column(name = "kneeFlexLSd")
    private String kneeFlexLSd;
    @Column(name = "ankleEverR")
    private String ankleEverR;
    @Column(name = "ankleEverL")
    private String ankleEverL;
    @Column(name = "ankleEverRSd")
    private String ankleEverRSd;
    @Column(name = "ankleEverLSd")
    private String ankleEverLSd;
    @Column(name = "ankleInvL")
    private String ankleInvL;
    @Column(name = "ankleInvR")
    private String ankleInvR;
    @Column(name = "ankleInvLSd")
    private String ankleInvLSd;
    @Column(name = "ankleInvRSD")
    private String ankleInvRSD;
    @Column(name = "ffAbaddLSd")
    private String ffAbaddLSd;
    @Column(name = "ffAbaddRSd")
    private String ffAbaddRSd;
    @Column(name = "ffAbaddL")
    private String ffAbaddL;
    @Column(name = "ffAbaddR")
    private String ffAbaddR;
    @Column(name = "legLengthR")
    private String legLengthR;
    @Column(name = "legLengthL")
    private String legLengthL;
    @Column(name = "qAngleR")
    private String qAngleR;
    @Column(name = "qAnkleL")
    private String qAnkleL;
    @Column(name = "bilateralPopR")
    private String bilateralPopR;
    @Column(name = "bilateralPopL")
    private String bilateralPopL;
    @Column(name = "bilateralPopRSd")
    private String bilateralPopRSd;
    @Column(name = "bilaterPopLSd")
    private String bilaterPopLSd;
}
