package com.example.gaitlabapp.controllers.Visits;

import javafx.collections.FXCollections;
import javafx.fxml.Initializable;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ComboBox;
import javafx.scene.control.RadioButton;

import java.net.URL;
import java.util.ResourceBundle;

public class VisitsDetailsMovementDisorder implements Initializable {
    public CheckBox CL0;
    public CheckBox CL1;
    public CheckBox CL2;
    public CheckBox CL3;
    public CheckBox CL4;
    public CheckBox CL5;
    public  CheckBox CL6;
    public CheckBox CL7;
    public CheckBox CL8;
    public CheckBox CL9;
    public CheckBox CL10;
    public CheckBox LL0;
    public CheckBox LL1;
    public CheckBox LL2;
    public CheckBox LL3;
    public CheckBox LL4;
    public CheckBox LL5;
    public CheckBox LL6;
    public CheckBox LL7;
    public CheckBox LL8;
    public CheckBox LL9;
    public CheckBox LL10;
    public CheckBox HL0;
    public CheckBox HL1;
    public CheckBox HL2;
    public CheckBox HL3;
    public CheckBox HL4;
    public CheckBox HL5;
    public CheckBox HL6;
    public CheckBox HL7;
    public CheckBox HL8;
    public CheckBox HL9;
    public CheckBox HL10;


    public  ComboBox<String> FMS5M;
    public  ComboBox<String> FMS50M;
    public  ComboBox<String> FMS500M;
    public ComboBox<String> GMFCSCombo;
    public ComboBox<String> CFCSComboBox;
    public ComboBox<String> MACSCombobox;
    public ComboBox hipRP;
    public ComboBox hipLP;
    public ComboBox hipRS;
    public ComboBox hipLS;
    public ComboBox hipExtRP;
    public ComboBox hipExtLP;
    public ComboBox hipExtLS;
    public ComboBox hipExtRS;
    public ComboBox hipAbdRP;
    public ComboBox hipAbdLP;
    public ComboBox hipAbdRS;
    public ComboBox hipAbdLS;
    public ComboBox hipIntRotRP;
    public ComboBox hipIntRotLP;
    public ComboBox hipIntRotRS;
    public ComboBox hipIntRotLS;
    public ComboBox hipExtRotRP;
    public ComboBox hipExtRotLP;
    public ComboBox hipExtRotRS;
    public ComboBox hipExtRotLS;
    public ComboBox ryderRP;
    public ComboBox ryderLP;
    public ComboBox ryderRS;
    public ComboBox ryderLS;
    public ComboBox kneeExtRP;
    public ComboBox kneeExtLP;
    public ComboBox kneeExtRS;
    public ComboBox kneeExtLS;
    public ComboBox extLagRP;
    public ComboBox extLagLP;
    public ComboBox extLagRS;
    public ComboBox extLagLS;
    public ComboBox kneeFlexRP;
    public ComboBox kneeFlexLP;
    public ComboBox kneeFlexRS;
    public ComboBox kneeFlexLS;
    public ComboBox popAngRP;
    public ComboBox popAngLP;
    public ComboBox popAngRS;
    public ComboBox popAngLS;
    public ComboBox biPopAngRP;
    public ComboBox biPopAngLP;
    public ComboBox elyTestRP;
    public ComboBox elyTestLP;
    public ComboBox dorsiFlexRP;
    public ComboBox dorsiFlexLP;
    public ComboBox dorsiExtRP;
    public ComboBox dorsiExtLP;
    public ComboBox plantarRP;
    public ComboBox plantarLP;
    public ComboBox plantarRS;
    public ComboBox plantarLS;
    public ComboBox ankleInvRP;
    public ComboBox ankleInvLP;
    public ComboBox ankleInvRS;
    public ComboBox ankleInvLS;
    public ComboBox ankleEverRP;
    public ComboBox ankleEverLP;
    public ComboBox ankleEverRS;
    public ComboBox ankleEverLS;
    public ComboBox tmaRP;
    public ComboBox tmaLP;
    public ComboBox tfaRP;
    public ComboBox tfaLP;
    public ComboBox ffRP;
    public ComboBox ffLP;
    public ComboBox calInvRP;
    public ComboBox calInvLP;
    public ComboBox calEverRP;
    public ComboBox calEverLP;
    public ComboBox legLengthRP;
    public ComboBox legLengthLP;
    public ComboBox kneeVarusRP;
    public ComboBox kneeVarusLP;
    public ComboBox TillipsoasLinterp;
    public ComboBox TillipsoasRinterp;
    public ComboBox TgluteMaxLinterp;
    public ComboBox TgluteMaxRinterp;
    public ComboBox TaddLinterp;
    public ComboBox TaddRinterp;
    public ComboBox TrecFemLinterp;
    public ComboBox TrecFemRInterp;
    public ComboBox TrecCatchLinterp;
    public ComboBox TrecCatchRinterp;
    public ComboBox TvastmedLinterp;
    public ComboBox TvastmedRInterp;
    public ComboBox ThamstringLinterp;
    public ComboBox ThamstringRinterp;
    public ComboBox TpostTibLinterp;
    public ComboBox TpostTibRInterp;
    public ComboBox TantLinterp;
    public ComboBox TantRInterp;
    public ComboBox TgastroLinterp;
    public ComboBox TgastroRinterp;
    public ComboBox TclonusLinterp;
    public ComboBox TclonusRinterp;
    public ComboBox TkneeJerLinterp;
    public ComboBox TkneeJerRinterp;
    public ComboBox RankJerLinterp;
    public ComboBox RankJerRinterp;
    public ComboBox TbabinLinterp;
    public ComboBox TbabinRinterp;
    public ComboBox TproxLinterp;
    public ComboBox TproxRinterp;
    public ComboBox TdistalLinterp;
    public ComboBox TdistalRinterp;
    public RadioButton PAMNum;
    public RadioButton PAMWrong;
    public RadioButton PAMflacc;
    public CheckBox AFwb;
    public CheckBox AFstand;
    public CheckBox AFwalk;
    public CheckBox AFrun;
    public CheckBox AFadl;
    public CheckBox AFtouch;
    public CheckBox AFmovement;
    public CheckBox AFother;
    public CheckBox AIsleep;
    public CheckBox AIads;
    public CheckBox AIschool;
    public CheckBox AIsports;
    public CheckBox AIfuncMob;
    public CheckBox AIother;


    @Override
    public void initialize(URL location, ResourceBundle resources) {
        /*
        Assigning all comboboxes their appropriate values
         */

        //General
        GMFCSCombo.getSelectionModel().selectFirst();
        MACSCombobox.getSelectionModel().selectFirst();
        CFCSComboBox.getSelectionModel().selectFirst();
        FMS500M.getSelectionModel().selectFirst();
        FMS5M.getSelectionModel().selectFirst();
        FMS50M.getSelectionModel().selectFirst();

        //PROM and Strength
        hipRP.getSelectionModel().selectFirst();
        hipLP.getSelectionModel().selectFirst();
        hipRS.getSelectionModel().selectFirst();
        hipLS.getSelectionModel().selectFirst();
        hipExtRP.getSelectionModel().selectFirst();
        hipExtLP.getSelectionModel().selectFirst();
        hipExtLS.getSelectionModel().selectFirst();
        hipExtRS.getSelectionModel().selectFirst();
        hipAbdRP.getSelectionModel().selectFirst();
        hipAbdLP.getSelectionModel().selectFirst();
        hipAbdLS.getSelectionModel().selectFirst();
        hipAbdRS.getSelectionModel().selectFirst();
        hipExtRotRP.getSelectionModel().selectFirst();
        hipExtRotLP.getSelectionModel().selectFirst();
        hipExtRotLS.getSelectionModel().selectFirst();
        hipExtRotRS.getSelectionModel().selectFirst();
        ryderRP.getSelectionModel().selectFirst();
        ryderLP.getSelectionModel().selectFirst();
        ryderRS.getSelectionModel().selectFirst();
        ryderLS.getSelectionModel().selectFirst();
        kneeExtRP.getSelectionModel().selectFirst();
        kneeExtLP.getSelectionModel().selectFirst();
        kneeExtRS.getSelectionModel().selectFirst();
        kneeExtLS.getSelectionModel().selectFirst();
        kneeFlexRP.getSelectionModel().selectFirst();
        kneeFlexLP.getSelectionModel().selectFirst();
        kneeFlexRS.getSelectionModel().selectFirst();
        kneeFlexLS.getSelectionModel().selectFirst();
        popAngRP.getSelectionModel().selectFirst();
        popAngLP.getSelectionModel().selectFirst();
        popAngRS.getSelectionModel().selectFirst();
        popAngLS.getSelectionModel().selectFirst();
        biPopAngRP.getSelectionModel().selectFirst();
        biPopAngLP.getSelectionModel().selectFirst();
        elyTestRP.getSelectionModel().selectFirst();
        elyTestLP.getSelectionModel().selectFirst();
        dorsiExtRP.getSelectionModel().selectFirst();
        dorsiExtLP.getSelectionModel().selectFirst();
        dorsiFlexLP.getSelectionModel().selectFirst();
        dorsiFlexRP.getSelectionModel().selectFirst();
        plantarRP.getSelectionModel().selectFirst();
        plantarLP.getSelectionModel().selectFirst();
        plantarRS.getSelectionModel().selectFirst();
        plantarLS.getSelectionModel().selectFirst();
        ankleInvRP.getSelectionModel().selectFirst();
        ankleInvLP.getSelectionModel().selectFirst();
        ankleInvRS.getSelectionModel().selectFirst();
        ankleInvLS.getSelectionModel().selectFirst();
        ankleEverRP.getSelectionModel().selectFirst();
        ankleEverLP.getSelectionModel().selectFirst();
        ankleEverRS.getSelectionModel().selectFirst();
        ankleEverLS.getSelectionModel().selectFirst();
        tmaRP.getSelectionModel().selectFirst();
        tmaLP.getSelectionModel().selectFirst();
        tfaLP.getSelectionModel().selectFirst();
        tfaRP.getSelectionModel().selectFirst();
        ffLP.getSelectionModel().selectFirst();
        ffRP.getSelectionModel().selectFirst();
        calInvLP.getSelectionModel().selectFirst();
        calInvRP.getSelectionModel().selectFirst();
        calEverLP.getSelectionModel().selectFirst();
        calEverRP.getSelectionModel().selectFirst();
        legLengthLP.getSelectionModel().selectFirst();
        legLengthRP.getSelectionModel().selectFirst();
        kneeVarusLP.getSelectionModel().selectFirst();
        kneeVarusRP.getSelectionModel().selectFirst();

        //Tone comboboxes
        TillipsoasLinterp.getSelectionModel().selectFirst();
        TillipsoasRinterp.getSelectionModel().selectFirst();
        TgluteMaxLinterp.getSelectionModel().selectFirst();
        TgastroRinterp.getSelectionModel().selectFirst();
        TaddLinterp.getSelectionModel().selectFirst();
        TaddRinterp.getSelectionModel().selectFirst();
        TrecFemLinterp.getSelectionModel().selectFirst();
        TrecFemRInterp.getSelectionModel().selectFirst();
        TrecCatchLinterp.getSelectionModel().selectFirst();
        TrecCatchRinterp.getSelectionModel().selectFirst();
        TvastmedLinterp.getSelectionModel().selectFirst();
        TvastmedRInterp.getSelectionModel().selectFirst();
        ThamstringLinterp.getSelectionModel().selectFirst();
        ThamstringRinterp.getSelectionModel().selectFirst();
        TpostTibLinterp.getSelectionModel().selectFirst();
        TpostTibRInterp.getSelectionModel().selectFirst();
        TantLinterp.getSelectionModel().selectFirst();
        TantRInterp.getSelectionModel().selectFirst();
        TgastroRinterp.getSelectionModel().selectFirst();
        TgastroLinterp.getSelectionModel().selectFirst();
        TclonusLinterp.getSelectionModel().selectFirst();
        TclonusRinterp.getSelectionModel().selectFirst();
        TkneeJerLinterp.getSelectionModel().selectFirst();
        TkneeJerRinterp.getSelectionModel().selectFirst();
        RankJerLinterp.getSelectionModel().selectFirst();
        RankJerRinterp.getSelectionModel().selectFirst();
        TbabinLinterp.getSelectionModel().selectFirst();
        TbabinRinterp.getSelectionModel().selectFirst();
        TproxLinterp.getSelectionModel().selectFirst();
        TproxRinterp.getSelectionModel().selectFirst();
        TdistalLinterp.getSelectionModel().selectFirst();
        TdistalRinterp.getSelectionModel().selectFirst();

        //Pain




    }
}
