package com.example.gaitlabapp.model.forms;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import jakarta.persistence.*;
import lombok.NoArgsConstructor;

@Getter
@Data
@Entity
@NoArgsConstructor
@Setter
@Table(name = "PROM")
public class IPromModel {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "promId")
    private Integer promId;
    @Column(name = "hipAbdR")
    private Integer hipAbdR;
    @Column(name = "hipAbdRInterp")
    private String hipAbdRInterp;
    @Column(name = "hipAbdL")
    private Integer hipAbdL;
    @Column(name = "hipAbdLInterp")
    private String hipAbdLInterp;
    @Column(name = "hipAbdSR")
    private String hipAbdSR;
    @Column(name = "hipAbdSRInterp")
    private String hipAbdSRInterp;
    @Column(name = "hipAbdSL")
    private String hipAbdSL;
    @Column(name = "hipAbdSLInterp")
    private String hipAbdSLInterp;
    @Column(name = "hipExtr")
    private Integer hipExtr;
    @Column(name = "hipExtrInterp")
    private String hipExtrInterp;
    @Column(name = "hipExtL")
    private Integer hipExtL;
    @Column(name = "hipExtLInterp")
    private String hipExtLInterp;
    @Column(name = "hipExtSR")
    private String hipExtSR;
    @Column(name = "hipExtSRInterp")
    private String hipExtSRInterp;
    @Column(name = "popRLow")
    private Integer popRLow;
    @Column(name = "popRHigh")
    private Integer popRHigh;
    @Column(name = "popRInterp")
    private String popRInterp;
    @Column(name = "popLLow")
    private Integer popLLow;
    @Column(name = "popLHigh")
    private Integer popLHigh;
    @Column(name = "popLInterp")
    private String popLInterp;
    @Column(name = "dorsiFR")
    private Integer dorsiFR;
    @Column(name = "dorsiFRInterp")
    private String dorsiFRInterp;
    @Column(name = "dorsiFL")
    private Integer dorsiFL;
    @Column(name = "dorsiFLInterp")
    private String dorsiFLInterp;
    @Column(name = "dorsiER")
    private Integer dorsiER;
    @Column(name = "dorsiERInterp")
    private String dorsiERInterp;
    @Column(name = "dorsiEL")
    private Integer dorsiEL;
    @Column(name = "dorsiELInterp")
    private String dorsiELInterp;
    @Column(name = "dorsiFSR")
    private String dorsiFSR;
    @Column(name = "dorsiFSRInterp")
    private String dorsiFSRInterp;
    @Column(name = "dorsiFSL")
    private String dorsiFSL;
    @Column(name = "dorsiFSLInterp")
    private String dorsiFSLInterp;
    @Column(name = "shoulderAbductionl")
    private Integer shoulderAbductionl;
    @Column(name = "shoulderAbdubctionr")
    private Integer shoulderAbdubctionr;
    @Column(name = "shoulderAbductionRInterp")
    private String shoulderAbductionRInterp;
    @Column(name = "shoulderAbductionLInterp")
    private String shoulderAbductionLInterp;
    @Column(name = "shoulderAbductionSL")
    private String shoulderAbductionSL;
    @Column(name = "shoulderAbdubctionSR")
    private String shoulderAbdubctionSR;
    @Column(name = "shoulderAbductionSLInterp")
    private String shoulderAbductionSLInterp;
    @Column(name = "shoulderAbductionSRInterp")
    private String shoulderAbductionSRInterp;
    @Column(name = "elbowExtL")
    private Integer elbowExtL;
    @Column(name = "elbowExtR")
    private Integer elbowExtR;
    @Column(name = "elbowExtLInterp")
    private String elbowExtLInterp;
    @Column(name = "elbowExtRInterp")
    private String elbowExtRInterp;
    @Column(name = "elbowExtSL")
    private String elbowExtSL;
    @Column(name = "elbowExtSR")
    private String elbowExtSR;
    @Column(name = "elbowExtSLInterp")
    private String elbowExtSLInterp;
    @Column(name = "elbowExtSRInterp")
    private String elbowExtSRInterp;
    @Column(name = "wristExtL")
    private Integer wristExtL;
    @Column(name = "wristExtR")
    private Integer wristExtR;
    @Column(name = "wristExtLInterp")
    private String wristExtLInterp;
    @Column(name = "wristExtRInterp")
    private String wristExtRInterp;
    @Column(name = "wristExtSR")
    private String wristExtSR;
    @Column(name = "wristExtSL")
    private String wristExtSL;
    @Column(name = "wristExtSLInterp")
    private String wristExtSLInterp;
    @Column(name = "wristExtSRInterp")
    private String wristExtSRInterp;
    @Column(name = "tfaL")
    private String tfaL;
    @Column(name = "tfaR")
    private String tfaR;
    @Column(name = "tfaRInterp")
    private String tfaRInterp;
    @Column(name = "tfaLInterp")
    private String tfaLInterp;
    @Column(name = "calcanealInv")
    private String calcanealInv;
    @Column(name = "calcanealEver")
    private String calcanealEver;
    @Column(name = "kneeVargus")
    private String kneeVargus;
    @Column(name = "elyTest")
    private String elyTest;
    @Column(name = "elyL")
    private Integer elyL;
    @Column(name = "elyR")
    private Integer elyR;
    @Column(name = "elyRInterp")
    private String elyRInterp;
    @Column(name = "elyLInterp")
    private String elyLInterp;
    @Column(name = "plantar")
    private String plantar;
    @Column(name = "plantarR")
    private Integer plantarR;
    @Column(name = "plantarL")
    private Integer plantarL;
    @Column(name = "plantarLInterp")
    private String plantarLInterp;
    @Column(name = "plantarRInterp")
    private String plantarRInterp;
    @Column(name = "hipFlexR")
    private String hipFlexR;
    @Column(name = "hipFlexRInterp")
    private String hipFlexRInterp;
    @Column(name = "hipFlexL")
    private String hipFlexL;
    @Column(name = "hipFlexLInterp")
    private String hipFlexLInterp;
    @Column(name = "hipExtR")
    private String hipExtR;
    @Column(name = "hipExtRInterp")
    private String hipExtRInterp;
    @Column(name = "hipIntRotL")
    private String hipIntRotL;
    @Column(name = "hipIntRotR")
    private String hipIntRotR;
    @Column(name = "hipIntRotRInterp")
    private String hipIntRotRInterp;
    @Column(name = "hipIntRotLInterp")
    private String hipIntRotLInterp;
    @Column(name = "kneeIntRotL")
    private String kneeIntRotL;
    @Column(name = "kneeIntRotRInterp")
    private String kneeIntRotRInterp;
    @Column(name = "kneeIntRotLInterp")
    private String kneeIntRotLInterp;
    @Column(name = "kneeIntRotR")
    private String kneeIntRotR;
    @Column(name = "kneeExtR")
    private String kneeExtR;
    @Column(name = "kneeExtL")
    private String kneeExtL;
    @Column(name = "kneeExtRInterp")
    private String kneeExtRInterp;
    @Column(name = "kneeExtLInterp")
    private String kneeExtLInterp;
    @Column(name = "kneeFlexR")
    private String kneeFlexR;
    @Column(name = "kneeFlexL")
    private String kneeFlexL;
    @Column(name = "kneeFlexRInterp")
    private String kneeFlexRInterp;
    @Column(name = "kneeFlexLInterp")
    private String kneeFlexLInterp;
    @Column(name = "ankleEverR")
    private String ankleEverR;
    @Column(name = "ankleEverL")
    private String ankleEverL;
    @Column(name = "ankleEverRInterp")
    private String ankleEverRInterp;
    @Column(name = "ankleEverLInterp")
    private String ankleEverLInterp;
    @Column(name = "ankleInvL")
    private String ankleInvL;
    @Column(name = "ankleInvR")
    private String ankleInvR;
    @Column(name = "ankleInvLInterp")
    private String ankleInvLInterp;
    @Column(name = "ankleInvLInterp")
    private String ankleInvRInterp;
    @Column(name = "ffAbaddLInterp")
    private String ffAbaddLInterp;
    @Column(name = "ffAbaddRInterp")
    private String ffAbaddRInterp;
    @Column(name = "ffAbaddL")
    private String ffAbaddL;
    @Column(name = "ffAbaddR")
    private String ffAbaddR;
    @Column(name = "legLengthR")
    private String legLengthR;
    @Column(name = "legLengthL")
    private String legLengthL;
    @Column(name = "qAngleR")
    private String qAngleR;
    @Column(name = "qAnkleL")
    private String qAnkleL;
    @Column(name = "bilateralPopR")
    private String bilateralPopR;
    @Column(name = "bilateralPopL")
    private String bilateralPopL;
    @Column(name = "bilateralPopRInterp")
    private String bilateralPopRInterp;
    @Column(name = "bilaterPopLInterp")
    private String bilaterPopLInterp;
    @Column(name = "hipFlexStrenR")
    private String hipFlexStrenR;
    @Column(name = "hipFlexStrenL")
    private String hipFlexStrenL;
    @Column(name = "hipExtStrenR")
    private String hipExtStrenR;
    @Column(name = "hipExtStrenL")
    private String hipExtStrenL;
    @Column(name = "hipAbdStrenR")
    private String hipAbdStrenR;
    @Column(name = "hipAbdStrenL")
    private String hipAbdStrenL;
    @Column(name = "hipIntRotStrenL")
    private String hipIntRotStrenL;
    @Column(name = "hipIntRotStrenR")
    private String hipIntRotStrenR;
    @Column(name = "hipExtRotStrenL")
    private String hipExtRotStrenL;
    @Column(name = "hipExtRotStrenR")
    private String hipExtRotStrenR;
    @Column(name = "ryderTestR")
    private String ryderTestR;
    @Column(name = "ryderTestL")
    private String ryderTestL;
    @Column(name = "kneeFlexStrenR")
    private String kneeFlextStrenR;
    @Column(name = "kneeFlexStrenL")
    private String kneeFlextStrenL;
    @Column(name = "ExtLagStrenR")
    private String ExtLagStrenR;
    @Column(name = "ExtLagStrenL")
    private String ExtLagStrenL;
    @Column(name = "PopAngStrenR")
    private String PopAngStrenR;
    @Column(name = "PopAngStrenL")
    private String PopAngStrenL;
    @Column(name = "PlantarStrenR")
    private String PlantarStrenR;
    @Column(name = "PlantarStrenL")
    private String PlantarStrenL;
    @Column(name = "AnkInvStrenR")
    private String AnkInvStrenR;
    @Column(name = "AnkInvStrenL")
    private String AnkInvStrenL;
    @Column(name = "ryderTestStrenL")
    private String ryderTestStrenL;
    @Column(name = "ryderTestStrenR")
    private String ryderTestStrenR;
    @Column(name = "extLagR")
    private String extLagR;
    @Column(name = "extLagL")
    private String extLagL;
    @Column(name = "popAngR")
    private String popAngR;
    @Column(name = "popAngL")
    private String popAngL;
    @Column(name = "ankleInvStrengL")
    private String ankleInvStrengL;
    @Column(name = "ankleInvStrengR")
    private String ankleInvStrengR;
    @Column(name = "ankleEvStrengR")
    private String ankleEvStrengR;
    @Column(name = "ankleEvStrengL")
    private String ankleEvStrengL;


}
